// Generated by gencpp from file clustering/arr.msg
// DO NOT EDIT!


#ifndef CLUSTERING_MESSAGE_ARR_H
#define CLUSTERING_MESSAGE_ARR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace clustering
{
template <class ContainerAllocator>
struct arr_
{
  typedef arr_<ContainerAllocator> Type;

  arr_()
    : data()  {
    }
  arr_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::clustering::arr_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clustering::arr_<ContainerAllocator> const> ConstPtr;

}; // struct arr_

typedef ::clustering::arr_<std::allocator<void> > arr;

typedef boost::shared_ptr< ::clustering::arr > arrPtr;
typedef boost::shared_ptr< ::clustering::arr const> arrConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clustering::arr_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clustering::arr_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::clustering::arr_<ContainerAllocator1> & lhs, const ::clustering::arr_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::clustering::arr_<ContainerAllocator1> & lhs, const ::clustering::arr_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace clustering

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::clustering::arr_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clustering::arr_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clustering::arr_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clustering::arr_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clustering::arr_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clustering::arr_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clustering::arr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "420cd38b6b071cd49f2970c3e2cee511";
  }

  static const char* value(const ::clustering::arr_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x420cd38b6b071cd4ULL;
  static const uint64_t static_value2 = 0x9f2970c3e2cee511ULL;
};

template<class ContainerAllocator>
struct DataType< ::clustering::arr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clustering/arr";
  }

  static const char* value(const ::clustering::arr_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clustering::arr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] data\n"
;
  }

  static const char* value(const ::clustering::arr_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clustering::arr_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arr_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clustering::arr_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clustering::arr_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLUSTERING_MESSAGE_ARR_H
