// Generated by gencpp from file clustering/arrofarr.msg
// DO NOT EDIT!


#ifndef CLUSTERING_MESSAGE_ARROFARR_H
#define CLUSTERING_MESSAGE_ARROFARR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <clustering/arr.h>

namespace clustering
{
template <class ContainerAllocator>
struct arrofarr_
{
  typedef arrofarr_<ContainerAllocator> Type;

  arrofarr_()
    : header()
    , data()  {
    }
  arrofarr_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::clustering::arr_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::clustering::arr_<ContainerAllocator> >> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::clustering::arrofarr_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clustering::arrofarr_<ContainerAllocator> const> ConstPtr;

}; // struct arrofarr_

typedef ::clustering::arrofarr_<std::allocator<void> > arrofarr;

typedef boost::shared_ptr< ::clustering::arrofarr > arrofarrPtr;
typedef boost::shared_ptr< ::clustering::arrofarr const> arrofarrConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clustering::arrofarr_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clustering::arrofarr_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::clustering::arrofarr_<ContainerAllocator1> & lhs, const ::clustering::arrofarr_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::clustering::arrofarr_<ContainerAllocator1> & lhs, const ::clustering::arrofarr_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace clustering

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::clustering::arrofarr_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clustering::arrofarr_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clustering::arrofarr_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clustering::arrofarr_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clustering::arrofarr_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clustering::arrofarr_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clustering::arrofarr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "90c050f06f51bd327653eec13a1b23de";
  }

  static const char* value(const ::clustering::arrofarr_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x90c050f06f51bd32ULL;
  static const uint64_t static_value2 = 0x7653eec13a1b23deULL;
};

template<class ContainerAllocator>
struct DataType< ::clustering::arrofarr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clustering/arrofarr";
  }

  static const char* value(const ::clustering::arrofarr_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clustering::arrofarr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"clustering/arr[] data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: clustering/arr\n"
"float32[] data\n"
;
  }

  static const char* value(const ::clustering::arrofarr_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clustering::arrofarr_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arrofarr_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clustering::arrofarr_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clustering::arrofarr_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::clustering::arr_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLUSTERING_MESSAGE_ARROFARR_H
