// Generated by gencpp from file clustering/CoordinateList.msg
// DO NOT EDIT!


#ifndef CLUSTERING_MESSAGE_COORDINATELIST_H
#define CLUSTERING_MESSAGE_COORDINATELIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <clustering/Coordinates.h>

namespace clustering
{
template <class ContainerAllocator>
struct CoordinateList_
{
  typedef CoordinateList_<ContainerAllocator> Type;

  CoordinateList_()
    : header()
    , size(0)
    , ConeCoordinates()  {
    }
  CoordinateList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , size(0)
    , ConeCoordinates(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _size_type;
  _size_type size;

   typedef std::vector< ::clustering::Coordinates_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::clustering::Coordinates_<ContainerAllocator> >> _ConeCoordinates_type;
  _ConeCoordinates_type ConeCoordinates;





  typedef boost::shared_ptr< ::clustering::CoordinateList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clustering::CoordinateList_<ContainerAllocator> const> ConstPtr;

}; // struct CoordinateList_

typedef ::clustering::CoordinateList_<std::allocator<void> > CoordinateList;

typedef boost::shared_ptr< ::clustering::CoordinateList > CoordinateListPtr;
typedef boost::shared_ptr< ::clustering::CoordinateList const> CoordinateListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clustering::CoordinateList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clustering::CoordinateList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::clustering::CoordinateList_<ContainerAllocator1> & lhs, const ::clustering::CoordinateList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.size == rhs.size &&
    lhs.ConeCoordinates == rhs.ConeCoordinates;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::clustering::CoordinateList_<ContainerAllocator1> & lhs, const ::clustering::CoordinateList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace clustering

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::clustering::CoordinateList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clustering::CoordinateList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clustering::CoordinateList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clustering::CoordinateList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clustering::CoordinateList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clustering::CoordinateList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clustering::CoordinateList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a654c3f6014eca7e59fb10e9650784d4";
  }

  static const char* value(const ::clustering::CoordinateList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa654c3f6014eca7eULL;
  static const uint64_t static_value2 = 0x59fb10e9650784d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::clustering::CoordinateList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clustering/CoordinateList";
  }

  static const char* value(const ::clustering::CoordinateList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clustering::CoordinateList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint8 size\n"
"clustering/Coordinates[] ConeCoordinates\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: clustering/Coordinates\n"
"uint8 size\n"
"uint8 reconsize\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 colour\n"
"float32[] left\n"
"float32[] right\n"
"float32[] front\n"
"float32[] back\n"
"float32[] top\n"
"float32[] bottom\n"
;
  }

  static const char* value(const ::clustering::CoordinateList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clustering::CoordinateList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.size);
      stream.next(m.ConeCoordinates);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CoordinateList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clustering::CoordinateList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clustering::CoordinateList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "size: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.size);
    s << indent << "ConeCoordinates[]" << std::endl;
    for (size_t i = 0; i < v.ConeCoordinates.size(); ++i)
    {
      s << indent << "  ConeCoordinates[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::clustering::Coordinates_<ContainerAllocator> >::stream(s, indent + "    ", v.ConeCoordinates[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLUSTERING_MESSAGE_COORDINATELIST_H
